# H2 Plugin Configuration
plugin.h2.schema=PUBLIC
plugin.h2.user=gasw
plugin.h2.password=gasw
plugin.h2.server.enabled=true
plugin.h2.server.host=localhost
plugin.h2.server.port=9092
plugin.h2.db.path=db/jobs